- Reintroduced supervisor as process manager - Uses last release of RTPproxy to override virtualization constraints
 Changes to be committed:
	modified:   Dockerfile
	modified:   init.sh
	modified:   rtpproxy
	modified:   rtpproxy.sh
	modified:   supervisord.conf

diff --git a/rtpproxy b/rtpproxy
--- a/rtpproxy
+++ b/rtpproxy
@@ -1,14 +1,81 @@
-# Defaults for rtpproxy
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          rtpproxy
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: RTP Proxy
+# Description:       Relay for VoIP media streams
+### END INIT INFO
 
-USER=kamailio
-GROUP=kamailio
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+NAME=rtpproxy
+DESC="RTP relay"
+DAEMON=/usr/local/bin/$NAME
+USER=$NAME
+GROUP=$USER
+PIDFILE="/var/run/$NAME/$NAME.pid"
+#PIDFILE="/var/run/$NAME.pid"
+PIDFILE_DIR=`dirname $PIDFILE`
+CONTROL_SOCK="unix:$PIDFILE_DIR/$NAME.sock"
 
-# The control socket.
-#CONTROL_SOCK="unix:/var/run/rtpproxy/rtpproxy.sock"
-# To listen on an UDP socket, uncomment this line:
-CONTROL_SOCK=udp:127.0.0.1:7722
+test -x $DAEMON || exit 0
+umask 002
 
-PRIV_IP=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -f1 -d'/')
+. /lib/lsb/init-functions
 
-# Additional options that are passed to the daemon.
-EXTRA_OPTS="-d WARN:LOG_LOCAL5 -l PUBLIC_IP -m 10000 -M 10010"
+# Include defaults if available
+if [ -f /etc/default/$NAME ] ; then
+	. /etc/default/$NAME
+fi
+
+DAEMON_OPTS="-s $CONTROL_SOCK -u $USER:$GROUP -p $PIDFILE $EXTRA_OPTS"
+
+if [ ! -d "$PIDFILE_DIR" ];then
+	mkdir "$PIDFILE_DIR"
+    chown $USER:$GROUP "$PIDFILE_DIR"
+fi
+
+set -e
+
+case "$1" in
+  start)
+	echo -n "Starting $DESC: "
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
+	echo "$NAME."
+	;;
+  stop)
+	echo -n "Stopping $DESC: "
+	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	echo "$NAME."
+	;;
+  status)
+	echo -n "Status $DESC: "
+	PID=$(cat $PIDFILE)
+	kill -0 $PID
+	rc=$?
+	# Check exit code
+	if [ "$rc" -ne 0 ]
+	then
+		echo "$NAME is NOT running."
+		exit 7
+	else
+		echo "$NAME is running with PID: $PID"
+	fi
+	;;
+  restart|force-reload)
+	echo -n "Restarting $DESC: "
+	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	sleep 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
+	echo "$NAME."
+	;;
+  *)
+	N=/etc/init.d/$NAME
+	echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
+	exit 1
+	;;
+esac
+
+exit 0
